### ISSUE TITLE
PCF 1.6

### ISSUE THREAD

**Issue by phopper-pivotal** [krujos/scaleover-plugin#16]
With apps that run in PCF 1.6 or higher when two apps share same route plugin returns "Apps do not share a route!". With cf routes command we can clearly see the same route mapped to the two applications.

development   scale-paschal-cinerator         pivotalpoc.scratch-charter.net                        scale-demo-v1.0,scale-demo-v1.1
development   scale-nonobstetrical-trotter    pivotalpoc.scratch-charter.net                        scale-demo-v1.1

**Comment by krujos** [comment]
Dea's or diego?, can you run it with CF_TRACE=true

**Comment by phopper-pivotal** [comment]
Diego. Will grab trace output and forward.

**Comment by superbeeny** [comment]
+1

**Comment by superbeeny** [comment]
Looks like the cli output is coming as 1 line now, so the array is of length 1 here - https://github.com/krujos/scaleover-plugin/blob/master/scaleover_plugin.go#L160

**Comment by phopper-pivotal** [comment]
Sorry guys been on site at clients last two-days. But it appears Nick beat
me to the details.

**Comment by krujos** [comment]
Thanks guys, I'll get it sorted this weekend.

**Comment by krujos** [comment]
Fixed with [1f866b28f1396be33fbfc388e2aed5969ef5ee34](https://github.com/krujos/scaleover-plugin/commit/1f866b28f1396be33fbfc388e2aed5969ef5ee34)

Will be available via plugin repo when https://github.com/cloudfoundry-incubator/cli-plugin-repo/pull/70 is merged. Until then the bins are in or build from source.

**Comment by phopper-pivotal** [comment]
Looking good, thanks Joshua. One item of note - the scale over time period
appears to not be adhering value provided. set to 10 s and it runs bump
up/down every second after 1st iteration.

cf scaleover scale-demo-v1.0 scale-demo-v1.1 10s

For instance;
1: wait 10 seconds
2: wait 1 second
3: wait 1 second
... and so on

**Comment by krujos** [comment]
how many ais do you have? I did a quick test with 4 instances over 30 seconds and it divided the way I expected it too. Can you help me understand more about you're setup so I can repro

**Comment by phopper-pivotal** [comment]
Sure let me capture details. I start with 10 and 1 instance of each
app then scale over at rate of 10s (or 30s).
