### ISSUE TITLE
plugin needs to pretty print

### ISSUE THREAD

**Issue by krujos** [krujos/scaleover-plugin#5]

**Comment by guidowb** [comment]
PR #7 includes code for both interactive and non-interactive output:

➜  scaleover-plugin git:(cleanup) ✗ cf scaleover mingming-controller mingming-worker 20
mingming-controller (stopped)  >>>>>>>>>> mingming-worker (started) 

➜  scaleover-plugin git:(cleanup) ✗ cf scaleover mingming-worker mingming-controller 20 | cat
mingming-worker (started) 10 instances, mingming-controller (stopped) 0 instances
mingming-worker (started) 9 instances, mingming-controller (started) 1 instances
mingming-worker (started) 8 instances, mingming-controller (started) 2 instances
mingming-worker (started) 7 instances, mingming-controller (started) 3 instances
mingming-worker (started) 6 instances, mingming-controller (started) 4 instances
mingming-worker (started) 5 instances, mingming-controller (started) 5 instances
mingming-worker (started) 4 instances, mingming-controller (started) 6 instances
mingming-worker (started) 3 instances, mingming-controller (started) 7 instances
mingming-worker (started) 2 instances, mingming-controller (started) 8 instances
mingming-worker (started) 1 instances, mingming-controller (started) 9 instances
mingming-worker (stopped) 0 instances, mingming-controller (started) 10 instances
